[package]
name = "resonara"
version = "0.1.0"
edition = "2024"
[dependencies]
log = "=0.4.34"
resonara-core = { path = "../resonara-core" }
resonara-platform = { path = "../resonara-platform" }
[target.'cfg(not(target_os = "scarlet"))'.dependencies]
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "4005841e514690f3328c6e09b8b2b77656fa07de", default-features = false, features = ["std", "platform-winit"] }

[target.'cfg(target_os = "scarlet")'.dependencies]
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "4005841e514690f3328c6e09b8b2b77656fa07de", default-features = false, features = ["std", "platform-sws"] }
