[package]
name = "resonara"
version = "0.1.0"
edition = "2024"
[dependencies]
log = "=0.4.34"
resonara-core = { path = "../resonara-core" }
resonara-platform = { path = "../resonara-platform" }
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "cdd852eb22678b7b0d1c7e035c1f2b2ba4d057a7", default-features = false, features = ["std", "platform-winit"] }
