[workspace]
resolver = "2"
members = ["crates/resonara-clap", "crates/resonara-core", "crates/resonara-platform", "crates/resonara-app", "vendor/sws-protocol", "plugins/resonara-freeverb/editor"]
[patch."https://github.com/petitstrawberry/Scarlet"]
sws-protocol = { path = "vendor/sws-protocol" }
[workspace.dependencies]
clap-sys = "=0.5.0"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
hound = "3.5"
[profile.dev]
debug = 0
[profile.test]
debug = 0
