[package]
name = "resonara-platform"
version = "0.1.0"
edition = "2024"
[dependencies]
resonara-core = { path = "../resonara-core" }
[target.'cfg(not(target_os = "scarlet"))'.dependencies]
cpal = "0.15.3"

[target.'cfg(target_os = "scarlet")'.dependencies]
sas-client = { git = "https://github.com/petitstrawberry/Scarlet", rev = "d3b1c05127d4df3616f988b81a99f616e8a88064", default-features = false, features = ["std"] }
scarlet-os = { git = "https://github.com/petitstrawberry/Scarlet", rev = "d3b1c05127d4df3616f988b81a99f616e8a88064", default-features = false, features = ["std"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("scarlet"))'] }
