[package]
name = "resonara-clap"
version = "0.1.0"
edition = "2024"

[dependencies]
scarlet-clap-gui = { path = "../scarlet-clap-gui" }
clap-sys = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "=0.6.4"
objc2-foundation = { version = "=0.3.2", features = ["NSString", "NSThread"] }
objc2-app-kit = { version = "=0.3.2", features = ["NSApplication", "NSWindow", "NSView", "NSResponder", "NSGraphics"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("scarlet"))'] }

[target.'cfg(target_os = "scarlet")'.dependencies]
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "e2930e20acb108ff8ccf2a48dfb1a6629bbf42ab", default-features = false, features = ["std", "platform-sws"] }
